server.port=8088

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.open-in-view=false
spring.data.jpa.repositories.bootstrap_mode=default
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revision_type
spring.jpa.properties.org.hibernate.envers.revision_field_name=revision_id
spring.jpa.properties.org.hibernate.envers.modified_flag_suffix=_audit
spring.jpa.properties.org.hibernate.envers.default_schema=audit
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.properties.hibernate.connection.autocommit=false
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# FLOWABLE
# ===============================
flowable.process.async.executor.core-pool-size=10
flowable.process.async.executor.max-pool-size=50
flowable.process.async.executor.keep-alive-time=10000
flowable.process.async.executor.auto-activate=true
flowable.process.async-history.executor.async-job-acquisition-enabled=true
flowable.async-executor-activate=true
flowable.history-level=full
flowable.database-schema-update=true
flowable.eventregistry.enabled=false

# Charset
spring.datasource.hikari.connection-init-sql=SET client_encoding TO 'UTF8'

# ===============================
# Spring ACL
# ===============================
spring.jpa.properties.hibernate.default_schema=public
spring.sql.init.mode=always
spring.sql.init.platform=postgres

spring.profiles.active=@spring.profiles.active@



