# ===============================
# DATASOURCE ARCEP
# ===============================
spring.datasource.arcep.url=jdbc:postgresql://192.168.10.135:5432/ARCEP
spring.datasource.arcep.username=postgres
spring.datasource.arcep.password=postgres
spring.datasource.arcep.driver-class-name=org.postgresql.Driver

# ===============================
# DATASOURCE FLOWABLE
# ===============================
spring.datasource.flowable.url=jdbc:postgresql://192.168.10.135:5432/ARCEP
spring.datasource.flowable.username=postgres
spring.datasource.flowable.password=postgres
spring.datasource.flowable.driver-class-name=org.postgresql.Driver

# ===============================
# DATASOURCE AUDIT
# ===============================
spring.datasource.audit.url=jdbc:postgresql://192.168.10.135:5432/ARCEP-AUDIT
spring.datasource.audit.username=postgres
spring.datasource.audit.password=postgres
spring.datasource.audit.driver-class-name=org.postgresql.Driver

# ===============================
# DATASOURCE DIALECT CONFIG
# ===============================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# FEIGN KERNEL CLIENT CONFIG
# ===============================
feign.kernel.url=http://192.168.10.191:8002/mskernel/api
feign.kernel.name=msdevkv1

# ===============================
# FEIGN SELF CLIENT CONFIG
# ===============================
feign.reseau.url=http://192.168.10.191:8004/reseau/api
feign.reseau.name=implantation


# ===============================
# FEIGN REFERENTIEL CLIENT CONFIG
# ===============================
feign.referentiel.url=http://192.168.10.191:8004/referentiel/api
feign.referentiel.name=referentiel

# ===============================
# EUREKA CLIENT CONFIG
# ===============================

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=http://arcep-eureka.picosoft.biz:8101/eureka-server/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=192.168.10.191
eureka.instance.non-secure-port=8002
eureka.instance.metadata-map.management.context-path=/actuator
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}


# ===============================
# APPLICATION CONFIG
# ===============================

spring.application.name=reseau


# ===============================
# SERVER CONFIG
# ===============================

server.port=8080
server.servlet.context-path=/reseau

# ===============================
# MANAGMENT CONFIG
# ===============================

management.server.port=8080
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
